apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend
  labels:
    app: todo
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-todo-frontend-service
  template:
    metadata:
      labels:
        app: myapp-todo-frontend-service
    spec:
      containers:
        - name: frontend
          image: prabakaran32/frontend-app-k8:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URI
              value: "http://backend-service:8080"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"